### ISSUE TITLE
Could the create_config_plot app be made to handle configs with more than one OKS Session in them?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/appmodel#135]
I tried to run the `create_config_plot` app on the `example-configs.data.xml` file that is available in the `daqsystemtest` repo, and the app complained that it didn't like the fact that there was more than one Session object in the file.

```
(dbt) [biery@daq daqsystemtest]$ create_config_plot -f ./example-configs.data.xml -r local-1x1-config
2024-Oct-01 16:23:49,986 FATAL [appmodel::GraphBuilder::GraphBuilder(...) at /home/nfs/biery/dunedaq/01OctFDDevBleedingEdgeTest/sourcecode/appmodel/src/GraphBuilder.cpp:81] A graph tool error occured: Did not find one and only one Session instance in "./example-configs.data.xml" and its includes
```

Would it be possible to enhance the app so that it could handle configs with multiple OKS Sessions defined?  Of course, we would likely need to specify the OKS Session...

**Comment by jcfreeman2** [comment]
Handled via PR #139
